[tool.poetry]
name = "terramagic"
version = "0.1.0"
description = "A automate tool for terraform projects"
authors = ["Milton Jesus <milton.lima@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.9"
colorama = "^0.4.4"
click = "^8.0.3"
termcolor = "^1.1.0"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
flake8 = "^4.0.1"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
